# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c69cefa288f00c4eeb6569cadfe5acb85fb305d50e3208bef5b908ed278075f5015628c3420a929f75a4b54088d75e421f3b1018297ff1028a84655d5bab6349

test:
  secret_key_base: 80dfc0613fa5e1b1345310a5001ba98aaa10416dcbec6ceea33e20bc8c8702682b8e13a96bd194e96151b329ad3b7cc91a7d8a57db44c02b4de2063a261c5634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
